FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copiar requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar solo el script del consumidor
COPY consumer.py .

# Crear directorio para datos procesados
RUN mkdir -p /app/processed_data

# Comando para iniciar el consumidor
CMD ["python", "consumer.py"]