# Generated by Django 5.2.9 on 2025-12-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('vaccinated', models.BooleanField(default=False)),
            ],
        ),
    ]
